name: Downgraded Install

on:
    push:
        branches:
            - main

jobs:
    downgraded_install:
        runs-on: ubuntu-latest

        steps:
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.2
                    coverage: none

            # add some packages that could create confligs
            -   run: composer require rector/rector --ansi

            # wait for downgraded package to be deployed to avoid installing PHP 8.1 version
            -   run: sleep 30

            # install this package
            -   run: composer require rector/custom-phpspec-to-phpunit --ansi
